### ISSUE TITLE
Repositories and workspaces should be fetched in the order of activity

### ISSUE THREAD

**Issue by avikalpg** [Alokit-Innovations/reports#12]
When fetching repositories and workspaces, the API call should query for the more recently active repositories and workspaces first.

**Comment by deveshbedmutha1406** [comment]
I would like to contribute, will you please assign it to me.

**Comment by avikalpg** [comment]
Hi @deveshbedmutha1406, sorry I just saw your message. I have implemented this for Bitbucket. Let check and get back to you on whether it is needed for GitHub.
